server:
  port: 8000

spring:
  application:
    name: selly-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: selly-user-service
          uri: lb://SELLY-USER-SERVICE
          predicates:
            - Path=/selly-user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/selly-user-service/(?<segment>.*), /$\{segment}
        - id: selly-user-service
          uri: lb://SELLY-USER-SERVICE
          predicates:
            - Path=/selly-user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/selly-user-service/(?<segment>.*), /$\{segment}
        - id: selly-user-service
          uri: lb://SELLY-USER-SERVICE
          predicates:
            - Path=/selly-user-service/users/{userId}
            - Method=PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/selly-user-service/(?<segment>.*), /$\{segment}
            - CustomAuthorizationHeaderFilter
        - id: selly-user-service
          uri: lb://SELLY-USER-SERVICE
          predicates:
            - Path=/selly-user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/selly-user-service/(?<segment>.*), /$\{segment}
            - CustomAuthorizationHeaderFilter
        - id: selly-trade-service
          uri: lb://SELLY-TRADE-SERVICE
          predicates:
            - Path=/selly-trade-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, Logging filter
                preLogger: true
                postLogger: true
        - id: selly-exploration-service
          uri: lb://SELLY-EXPLORATION-SERVICE
          predicates:
            - Path=/selly-exploration-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, Logging filter
                preLogger: true
                postLogger: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

token:
  secret: '01234567890123456789012345678901234567890123456789'

