server:
  port: 8761 # eureka server? ????? ??

spring:
  application:
    name: discoveryservice # ???? ???? ??? ID? ??

eureka:
  client:
    register-with-eureka: false # ?? ???? ???? ???? ?????? ???? ????.
    fetch-registry: false # ????? ?? ? ??? ??? false
