server:
  port: 8081

spring:
  application:
    name: selly-user-service
  datasource:
#    url: jdbc:mariadb://localhost:3306/selly
    url: jdbc:mariadb://nftselly.com:3306/selly?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: S07P31B102
    password: Bh1736c3o!
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


eureka:
  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
     instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 15.165.177.117:8761/eureka
#      defaultZone: http://127.0.0.1:8761/eureka


logging:
  level:
    com.b102.sellyuserservice: DEBUG

token:
  expiration_time: 864000000 
  secret: '01234567890123456789012345678901234567890123456789'